import { Injectable, Inject } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import * as crypto from 'crypto';
import axios from 'axios';
import type { ISessionStore, PkceState } from './session.store';
import { SESSION_STORE } from './session-store.factory';

interface QFTokenResponse {
  access_token: string;
  refresh_token?: string;
  id_token?: string;
  expires_in: number;
  token_type: string;
}

interface QFIdTokenClaims {
  sub: string;
  first_name?: string;
  last_name?: string;
  email?: string;
}

function base64url(buf: Buffer): string {
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function generatePkcePair(): { codeVerifier: string; codeChallenge: string } {
  const codeVerifier = base64url(crypto.randomBytes(32));
  const hash = crypto.createHash('sha256').update(codeVerifier).digest();
  const codeChallenge = base64url(hash);
  return { codeVerifier, codeChallenge };
}

function randomHex(bytes = 16): string {
  return crypto.randomBytes(bytes).toString('hex');
}

function decodeIdToken(idToken: string): QFIdTokenClaims {
  const parts = idToken.split('.');
  if (parts.length < 2) throw new Error('Invalid id_token format');
  const payload = Buffer.from(parts[1], 'base64url').toString('utf8');
  return JSON.parse(payload) as QFIdTokenClaims;
}

@Injectable()
export class QfOAuthService {
  private readonly authBaseUrl: string;
  private readonly apiBaseUrl: string;
  private readonly clientId: string;
  private readonly clientSecret: string;
  private readonly redirectUri: string;

  constructor(
    private config: ConfigService,
    @Inject(SESSION_STORE) private store: ISessionStore,
  ) {
    this.authBaseUrl =
      config.get<string>('QF_USER_AUTH_BASE_URL') ?? 'https://oauth2.quran.foundation';
    this.apiBaseUrl = this.normalizeUserApiBaseUrl(
      config.get<string>('QF_USER_API_BASE_URL') ?? 'https://apis.quran.foundation/auth',
    );
    this.clientId =
      config.get<string>('QF_USER_CLIENT_ID') ?? config.get<string>('CLIENT_ID') ?? '';
    this.clientSecret =
      config.get<string>('QF_USER_CLIENT_SECRET') ?? config.get<string>('CLIENT_SECRET') ?? '';
    this.redirectUri = config.get<string>('QF_USER_REDIRECT_URI') ?? '';

    console.info('[QF OAuth] Config loaded', {
      authHost: this.safeHost(this.authBaseUrl),
      apiHost: this.safeHost(this.apiBaseUrl),
      redirectUriConfigured: Boolean(this.redirectUri),
      redirectUri: this.redirectUri || '<missing>',
      clientIdConfigured: Boolean(this.clientId),
      clientSecretConfigured: Boolean(this.clientSecret),
    });
  }

  private safeHost(url: string): string {
    try {
      return new URL(url).host;
    } catch {
      return '<invalid-url>';
    }
  }

  private normalizeUserApiBaseUrl(url: string): string {
    const trimmed = url.replace(/\/+$/, '');

    try {
      const parsed = new URL(trimmed);
      if (
        parsed.host === 'apis.quran.foundation' &&
        (parsed.pathname === '' || parsed.pathname === '/')
      ) {
        return `${trimmed}/auth`;
      }
    } catch {
      return trimmed;
    }

    return trimmed;
  }

  getDiagnostics() {
    return {
      authHost: this.safeHost(this.authBaseUrl),
      apiHost: this.safeHost(this.apiBaseUrl),
      redirectUriConfigured: Boolean(this.redirectUri),
      redirectUri: this.redirectUri || '<missing>',
      clientIdConfigured: Boolean(this.clientId),
      clientSecretConfigured: Boolean(this.clientSecret),
    };
  }

  /**
   * Build the QF authorize URL, persist PKCE state in the store keyed by
   * extState (the random value generated by the extension), and return the URL.
   */
  async buildAuthorizeUrl(extState: string): Promise<string> {
    const { codeVerifier, codeChallenge } = generatePkcePair();
    const oauthState = randomHex(16);
    const nonce = randomHex(16);

    const pkceData: PkceState = { oauthState, nonce, codeVerifier };
    await this.store.setPkceState(extState, pkceData);

    console.info('[QF OAuth] Starting login', {
      extState: this.shortId(extState),
      ...this.getDiagnostics(),
    });

    // Encode both oauthState and extState in the state param as "<oauthState>.<extState>"
    // so the callback can recover the extState without a separate lookup.
    const combinedState = `${oauthState}.${extState}`;

    const params = new URLSearchParams({
      response_type: 'code',
      client_id: this.clientId,
      redirect_uri: this.redirectUri,
      scope: 'openid offline_access user bookmark collection',
      state: combinedState,
      nonce,
      code_challenge: codeChallenge,
      code_challenge_method: 'S256',
    });

    return `${this.authBaseUrl}/oauth2/auth?${params.toString()}`;
  }

  private shortId(value: string): string {
    return value ? `${value.slice(0, 8)}…` : '<missing>';
  }

  /**
   * Exchange the authorization code for tokens. Returns user claims decoded
   * from the id_token plus raw tokens.
   */
  async exchangeCode(
    code: string,
    oauthState: string,
    extState: string,
  ): Promise<{
    sub: string;
    firstName: string;
    lastName: string;
    email: string;
    accessToken: string;
    refreshToken: string;
    accessTokenExpiresAt: number;
  }> {
    const pkce = await this.store.getPkceState(extState);
    if (!pkce) throw new Error('PKCE state not found or expired');
    if (pkce.oauthState !== oauthState) throw new Error('OAuth state mismatch (CSRF check failed)');

    await this.store.delPkceState(extState);

    console.info('[QF OAuth] Exchanging authorization code', {
      extState: this.shortId(extState),
      oauthState: this.shortId(oauthState),
      authHost: this.safeHost(this.authBaseUrl),
      redirectUri: this.redirectUri || '<missing>',
    });

    const params = new URLSearchParams({
      grant_type: 'authorization_code',
      code,
      redirect_uri: this.redirectUri,
      code_verifier: pkce.codeVerifier,
    });

    const response = await axios.post<QFTokenResponse>(
      `${this.authBaseUrl}/oauth2/token`,
      params.toString(),
      {
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        auth: { username: this.clientId, password: this.clientSecret },
      },
    );

    const { access_token, refresh_token, id_token, expires_in } = response.data;

    let sub = '';
    let firstName = '';
    let lastName = '';
    let email = '';

    if (id_token) {
      const claims = decodeIdToken(id_token);
      sub = claims.sub ?? '';
      firstName = claims.first_name ?? '';
      lastName = claims.last_name ?? '';
      email = claims.email ?? '';
    }

    return {
      sub,
      firstName,
      lastName,
      email,
      accessToken: access_token,
      refreshToken: refresh_token ?? '',
      accessTokenExpiresAt: Date.now() + expires_in * 1000,
    };
  }

  /**
   * Refresh the QF access token using the stored refresh token.
   * Returns updated tokens. Caller must persist the updated session.
   */
  async refreshAccessToken(refreshToken: string): Promise<{
    accessToken: string;
    refreshToken: string;
    accessTokenExpiresAt: number;
  }> {
    const params = new URLSearchParams({
      grant_type: 'refresh_token',
      refresh_token: refreshToken,
    });

    const response = await axios.post<QFTokenResponse>(
      `${this.authBaseUrl}/oauth2/token`,
      params.toString(),
      {
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        auth: { username: this.clientId, password: this.clientSecret },
      },
    );

    const { access_token, refresh_token, expires_in } = response.data;

    console.info('[QF OAuth] Refreshed user access token', {
      expiresInSeconds: expires_in,
      authHost: this.safeHost(this.authBaseUrl),
    });

    return {
      accessToken: access_token,
      refreshToken: refresh_token ?? refreshToken,
      accessTokenExpiresAt: Date.now() + expires_in * 1000,
    };
  }

  get userApiBase(): string {
    return this.apiBaseUrl;
  }

  get qfClientId(): string {
    return this.clientId;
  }
}
